---
title: "reading_data_from_web"
author: "Kaila Boyer"
date: "10/23/2021"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
library(httr) 
knitr::opts_chunk$set(
 
  fig.width = 6, 
  fig.asp = 6, 
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.color = "viridis", 
  ggplot2.continuous.fill = "viridis"
)

scale_color_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## NSDUH data 
```{r}
url <- "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_html <- read_html(url)

drug_use_df <- drug_use_html %>% 
                 html_table() %>% 
                 first()  %>% 
                 slice(-1)
```

## Learning Assessment 1 

```{r}
nyc <- read_html("https://www.bestplaces.net/cost_of_living/city/new_york/new_york") %>% 
  html_table(header = TRUE) %>% 
  first()
```


## CSS Selectors 

Get star wars data 
```{r}
sw_url <- "https://www.imdb.com/list/ls070150896/"

sw_html <- 
  read_html(sw_url) 

sw_titles <- sw_html %>% 
                 html_elements(".lister-item-header a") %>% 
                 html_text()

sw_revenue <- sw_html %>% 
                 html_elements(".text-small:nth-child(7) span:nth-child(5)") %>% 
                 html_text()

sw_df <- 
          tibble(
            title = sw_titles, 
            revenue = sw_revenue
          )
```


## Learning Assessment 2 - Napoleon Dynamite

```{r, eval = FALSE}

dynamite_url <- "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"


dynamite_html <- read_html(dynamite_url)

dynamite_reveiw_titles <- 
  dynamite_html %>% 
  html_elements(" .a-text-bold span") %>% 
  html_text()

dynamite_stars <- 
  dynamite_html %>% 
  html_elements("#cm_cr-review_list .review-rating") %>% 
  html_text()
  
```


## Try some APIs

Get some dadta from an API about water 

```{r}
water_df <- 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") %>% 
  content() 
```

Let's see what JSON looks like... 

```{r}
water_df1 <- GET("https://data.cityofnewyork.us/resource/ia2d-e54m.json") %>% 
  content("text") %>% 
  jsonlite::fromJSON() %>% 
  as_tibble()
```

## BRFSS Sata via API 

```{r}
brfss_df <- 
  GET("https://chronicdata.cdc.gov/resource/acme-vg9e.csv", 
      query = list("$limit" = 5000)) %>% 
  content()
```


## Pokemon API 

```{r}
poke_data <- GET("https://pokeapi.co/api/v2/pokemon/1") %>% content()
  
poke_data[["name"]]
poke_data[["height"]]
poke_data[["abilities"]]
```

